name: modelmongo-npm 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy-web:

    runs-on: ubuntu-latest

    steps:

    - name: Checking out Project 
      uses: actions/checkout@v3
    
    - name: Use Setup Node.js [18.x]
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'

    - name: Installing Dependencies
      run: npm ci

    - name: Compiling TypeScript
      run: tsc
  
    - name: Copy Files 
      run: cp package.json ./dist

    - name: Publishing Package
      working-directory: ./dist
      run: npm publish --access public 
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}    

